# splunk_app/default/indexes.conf

[infra_metrics]
homePath = $SPLUNK_DB/infra_metrics/db
coldPath = $SPLUNK_DB/infra_metrics/colddb
thawedPath = $SPLUNK_DB/infra_metrics/thaweddb
datatype = metric

[security_logs]
homePath = $SPLUNK_DB/security_logs/db
coldPath = $SPLUNK_DB/security_logs/colddb
thawedPath = $SPLUNK_DB/security_logs/thaweddb
datatype = event