# splunk_app/default/inputs.conf

[http]
disabled = 0
enableSSL = 0
port = 8088

[http://guardsre_telemetry_token]
disabled = 0
token = 00000000-0000-0000-0000-000000000000
indexes = infra_metrics,security_logs
sourcetype = _json