# splunk_app/default/savedsearches.conf

[sre_storage_iops_anomaly]
search = index=infra_metrics sourcetype=_json storage_cluster="vault-01a" \
| streamstats window=6 current=f avg(iops_read) as avg_iops statsddev(iops_read) as dev_iops \
| eval upper_bound = avg_iops + (3 * dev_iops) \
| eval is_anomaly = if(iops_read > upper_bound AND iops_read > 5000, 1, 0) \
| filter is_anomaly == 1
dispatch.earliest_time = -15m
dispatch.latest_time = now
cron_schedule = */1 * * * *
enableSched = 1