# splunk_app/default/savedsearches.conf

[sre_storage_iops_anomaly]
search = index=infra_metrics sourcetype=metric_json storage_cluster="vault-01a" \
| streamstats window=6 current=f avg(metric_name:iops_read) as avg_iops stdev(metric_name:iops_read) as dev_iops \
| eval upper_bound = avg_iops + (3 * dev_iops) \
| eval is_anomaly = if('metric_name:iops_read' > upper_bound AND 'metric_name:iops_read' > 5000, 1, 0) \
| where is_anomaly=1
dispatch.earliest_time = -15m
dispatch.latest_time = now
cron_schedule = */1 * * * *
enableSched = 1